### ISSUE TITLE
Store Profile info in localStorage?

### ISSUE THREAD

**Issue by i8ramin** [andreareginato/oauth-ng#35]
I notice that every time you refresh the page, the profile endpoint is hit. This is wasteful. How about storing the profile data in local/session storage on successful login?

**Comment by elwin1234** [comment]
Local storage seems possible at current master branch? (and according to documentation: http://andreareginato.github.io/oauth-ng/#configurations). What about tags 0.3.9 and 0.3.10 ( I see a reference to 0.3.10 in a commit message?

**Comment by bramski** [comment]
This was implemented by: https://github.com/andreareginato/oauth-ng/pull/72
