### ISSUE TITLE
JSHint reports some issues with the codebase

### ISSUE THREAD

**Issue by pavelhoral** [andreareginato/oauth-ng#44]
The code is pretty nice and compact in its current form. However I would suggest taking another look at the code style and errors reported by JSHint. 

For example instead of this:

    if (!token)           { return loggedOut() } // without access token it's logged out

preferr this:

    if (!token) { 
        return loggedOut(); // without access token it's logged out
    }

If not changing the style (thats just suggestion), the errors should be fixed (missing semicolons etc.). By the way feel free to close if you disagree as I don't feel strongly about this.

**Comment by m00s** [comment]
Fixed in 851232496f80b25631179213c749e384dca4e277
