### ISSUE TITLE
Angular 1.3 support

### ISSUE THREAD

**Issue by vertiman** [andreareginato/oauth-ng#64]
It seems to work in brief testing.  Any reason you're constrained to ~1.2.26?  Just haven't had a chance to bump the version yet?

**Comment by muymoo** [comment]
+1 We might be able to submit a PR in a little bit.

**Comment by muymoo** [comment]
https://github.com/andreareginato/oauth-ng/pull/67
Can we get a 0.3.7 tag?

**Comment by Sergey-Ryabov** [comment]
Is it support version 1.3.x of the angularjs?
