### ISSUE TITLE
How does authorization code flow work without a server side component?

### ISSUE THREAD

**Issue by kurtfm** [andreareginato/oauth-ng#66]
Typically a purely client-side solution would only allow for 'implicit' flow since no client_secret is needed to get the access_token.  Without going too far with this I was wondering how you are doing the authorization code flow without storing the client_secret in client side code or is the intention that the code be picked up by the server and the access token call be done server side?

**Comment by andreareginato** [comment]
If I got the question right, there no way at the moment to apply the authorization code flow on client side. All you can do is to get the token on server side and then store it in the AccessToken class.

**Comment by kurtfm** [comment]
Ok, sorry, I think this is just my fault for not really trying things out before I asked.  Thanks for taking the time to reply.
