### ISSUE TITLE
Handling invalidated tokens and 401 statuses

### ISSUE THREAD

**Issue by geoah** [andreareginato/oauth-ng#69]
I'm trying to figure how how invalidated tokens (on the server side) should be handled.

Once a user logs in successfully the token is stored locally and on each page reload the token is retrieved and the profile is being requested.
I assumed that if the profile returns a `401` HTTP code it would remove the locally stored token and require the user to login again.

What would be the "correct" or suggested way to do this?

Additionally how would an `$http` response interceptor force the user to re-login when an `401` HTTP status is received?
This would be useful for custom made requests using the token.

Thank you and I do apologise if this is common knowledge around here. :)

**Comment by m00s** [comment]
Hi @geoah, you can find some discussions about it in issue #17.
