### ISSUE TITLE
Code Minification 

### ISSUE THREAD

**Issue by meloks** [andreareginato/oauth-ng#71]
Hi,

We were testing your nice oauth-ng module and came across the issue with the code minification.

When included in an app and minified with browserify, we see the classical Angular error: [$injector:unpr] Unknown provider: aProvider <- a <- Profile <- oauthDirective
 
When the module code is modified as suggested at https://docs.angularjs.org/error/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-%20Profile%20%3C-%20oauthDirective, it seems work.

Is it something you are planning to change it in the future?

**Comment by Sereph** [comment]
I had the same issue but was able to solve it using the gulp-ng-annotate module as part of our build process: https://www.npmjs.com/package/gulp-ng-annotate 
This is what we are using as a temporary work-around until the code is updated.

**Comment by AnimaLupi** [comment]
I made a pull request with the inline annotations, hopefully it can be merged to fix this issue.

https://github.com/andreareginato/oauth-ng/pull/75

Ciao
