### ISSUE TITLE
`setExpiresAtEvent' is fired immediately when expiration date is larger than 1193 hours

### ISSUE THREAD

**Issue by elwin1234** [andreareginato/oauth-ng#80]
The maximum timeout for javascripts setInterval function (function that angular's $interval wraps) is: 4294967295 (32 bit int). This means 4294967295ms = 1193 hours = 49.71 days as max timeout. Some api's provide tokens that are valid for 3 months or longer. Because this time exceeds the maximum value the 'oauth:expired' is fired immediately.

**Comment by m00s** [comment]
Hi @elwin1234.

`setTimeout` limit is **2147483647 ms** / 1000 / 60 / 60 / 24  ~= **24,85 days**.

We could wrap `setTimeout` in a recursive function but I think we should find a better way to notify the _token-expired_ event.

Any suggestion?

**Comment by anilanar** [comment]
I guess if it is greater than 2147483647 ms, omitting `setInterval` call that fires `oauth:expired` is fine.
