### ISSUE TITLE
Can't get the demo site working with an example application on Github

### ISSUE THREAD

**Issue by matrixagent** [andreareginato/oauth-ng#81]
Hi there,

I was trying to get this to work with Github OAuth. I cloned the demo project and modified the config in main.html:

```
<oauth
      site="https://github.com/login"
      client-id="supersecret12345"
      redirect-uri="http://localhost:9000"
      profile-uri="https://api.github.com/user"
      scope="user">
    </oauth>
```

The Github application of course also has *http://localhost:9000* as redirect url. Clicking on *Sign In* does lead me to Github, where I see that my demo application wants access, so far so good. When I grant it, I'm redirected to *http://localhost:9000/?code=1234567da5307f351420&state=%2F*, so it looks like it kinda works, but oauth-ng doesn't recognize the reply from Github and gets stuck in the middle of the OAuth2 exchange process. I've tried to get it to work by forcing a JSON reply from Github, but I didn't manage to force an Accept-header into the requests that oauth-ng is sending.

I'm fairly new with angular-js, which is why I'm asking here a little sooner rather then spend more hours trying to find a solution on Google – should Github OAuth work with the demo page, or do I misunderstand something else and am destined to fail at my attempt anyway?

I'd be grateful for any input!

Thanks, Manuel

Edit: After looking into it some more, it seems to me that it won't be possible to use oauth-ng with Github OAuth, as they don't support the "implicit flow" version of the protocol. Correct?

**Comment by m00s** [comment]
@matrixagent you should be able to login using the [authorization grant](https://github.com/andreareginato/oauth-ng#authorization-code-flow) supported by both github and oauth-ng. Let me now and post your code if you need help

**Comment by hawkerm** [comment]
I'm also trying to do the code flow based authentication vs. the implicit flow.  The library says it supports it, but then I don't see it parsing the authorization code and doing another loop in order to get the actual access token.  Am I missing something?

I just get sent back to my page with the auth code in the query string //site/?code=ASDFASDF...

**Comment by m00s** [comment]
@hawkerm you're right, the authorization code is not available now and it will be added soon. The readme was never updated so I'll fix it today. Thank you guys

**Comment by tomsowerby** [comment]
Hello thread,
What's the status on this? I've just found this library and it's not clear if it's meant to do the code-to-token exchange part as well. Or if the authorization grant type is supported at all?
