### ISSUE TITLE
bower version 0.4.0 and dist/oauth-ng.js metnionning 0.3.10 

### ISSUE THREAD

**Issue by ronanquillevere** [andreareginato/oauth-ng#82]
Hello,

Versions seems not to be aligned in js and bower.

BR

**Comment by andreareginato** [comment]
@m00s is going to check it out pretty soon. Thanks for letting us know.

**Comment by m00s** [comment]
Seems PR #77 included the build and the source was not re-builded after the version bump, so actually the code is the same but versions diverge. I think we can fix this in the next release, rather than making one specifically.

**Comment by m00s** [comment]
Fixed with #79 merge
