### ISSUE TITLE
AccessToken.expired returns false for expired token

### ISSUE THREAD

**Issue by pavel-r** [andreareginato/oauth-ng#83]
In the timeout we got an "expired" event, but in the handler when we check **AccessToken.expired()** it returns false.
When we looked in the code, we found out that the **timeout** and **ExpiredInterceptor** defines expirety differently from **AccessToken.expired()** method.
ExpiredInterceptor Line 18:
```javascript
var expired = function(token) {
    return (token && token.expires_at && new Date(token.expires_at) < new Date())
  };
```
AccessToken Line 52:
```javascript
service.expired = function(){
        return (this.token && this.token.expires_at && this.token.expires_at<new Date());
};
```

**Comment by m00s** [comment]
Thank you @pavel-r, it is definitely a bug. Gonna fix it in the next release
