### ISSUE TITLE
Nonce support in oauth-element

### ISSUE THREAD

**Issue by errno3** [andreareginato/oauth-ng#87]
Hi guys,

is there any way to pass nonce in request? our IdProvider requires a nonce for implicit and hybrid clients. Thanks for any response.

Regards,
Erno

**Comment by andreareginato** [comment]
If I understood the question, you can use the state param.

**Comment by edtyl3r** [comment]
Hi there,
I can see that nonce has been added to the authorisation url but how do we supply the parameter in the directive?
Thanks,
Ed

**Comment by mattheffernan** [comment]
@edtyl3r just add ```nonce="true"``` on your directive.

**Comment by edtyl3r** [comment]
Thanks @mattheffernan . This was added in 246a13c

**Comment by rondoe** [comment]
please add that to the documentation. thx
