### ISSUE TITLE
Call login() from outside template

### ISSUE THREAD

**Issue by GregTurner** [andreareginato/oauth-ng#88]
Is there a way to call the directive's login() and logout() functions from outside the directive?

**Comment by andreareginato** [comment]
Not at the moment. One possible solution could be to add some events listeners into the directive.

**Comment by GregTurner** [comment]
Thanks for confirming. I like that idea about triggering an event.

The use-cases I'm looking for are:

1) add links to the bottom of a sign up page, eg already signed up?

2) non user initiated logout

I can call your services directly but it feels brittle.

**Comment by andreareginato** [comment]
Hi @GregTurner. For the use case 1 you could also duplicate the directive code and assign a [differente template](http://andreareginato.github.io/oauth-ng/#customizations). It should solve your problem. I didn't get the point 2.

In any case, events could be useful also in the future.

**Comment by GregTurner** [comment]
That'd work!  Great suggestion.

Re: UC#2: not important at this time
