### ISSUE TITLE
oauth:expired is fired twice when refreshing the token

### ISSUE THREAD

**Issue by pavel-r** [andreareginato/oauth-ng#91]
We refresh the token every time **oauth:expired** is fired. In the code that refreshes the token we call `AccessToken.setTokenFromString(tokenStr)`. However, `AccessToken` sets the `$interval` twice:
-First time it is set with an old value of **token.expires_at**, causing `time` to be negative and triggering **oauth:expired** immediately.
-Second time it is set with an updated(correct) value of **token.expires_at**, triggering **oauth:expired** before the token really expires.

Checking `if(time && time > 0)` in `setExpiresAtEvent` function can quickly fix the issue. Although, you may consider a better solution. Probably cleaning old token values before setting the new ones; or refactoring a bit `AccessToken`, so you don't have to call `setToken` twice in the `setTokenFromString` method.

**Comment by m00s** [comment]
Thanks @pavel-r for the suggestion. I think your solution can fix the issue for now, if you can please submit a PR, otherwise I'm gonna implement that in the next release.
We need to think a better long term solution then and refactoring that service is a good starting point.
